In [1]:
!pip install transformers accelerate torch pandas tqdm

Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (5.0.0)
Requirement already satisfied: accelerate in /usr/local/lib/python3.12/dist-packages (1.13.0)
Requirement already satisfied: torch in /usr/local/lib/python3.12/dist-packages (2.10.0+cu128)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (4.67.3)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from transformers) (3.29.0)
Requirement already satisfied: huggingface-hub<2.0,>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (1.11.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (26.1)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.22.2)
Requirement already satisfied: typer-slim in /usr/local/lib/python3.12/dist-packages (from transformers) (0.24.0)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.7.0)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from accelerate) (5.9.5)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch) (4.15.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch) (2025.3.0)
Requirement already satisfied: cuda-bindings==12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch) (12.9.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch) (3.4.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch) (1.13.1.3)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch) (3.6.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings==12.9.4->torch) (1.5.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.1)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (1.4.3)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (0.28.1)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (0.24.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch) (3.0.3)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (4.13.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (2026.4.22)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (3.13)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (0.16.0)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=1.3.0->transformers) (8.3.3)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=1.3.0->transformers) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=1.3.0->transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=1.3.0->transformers) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub<2.0,>=1.3.0->transformers) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub<2.0,>=1.3.0->transformers) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface-hub<2.0,>=1.3.0->transformers) (0.1.2)

In [2]:
import re
import pandas as pd
import torch
from tqdm import tqdm
from transformers import pipeline
from google.colab import files

In [3]:
import os

REPO_URL = "https://github.com/simona-wang/negotiation_arena.git"
PROJECT_DIR = "/content/negotiation_arena"

if not os.path.exists(PROJECT_DIR):
    !git clone {REPO_URL} {PROJECT_DIR}

DATA_DIR = os.path.join(PROJECT_DIR, "data")
RESULTS_DIR = os.path.join(PROJECT_DIR, "results")

os.makedirs(RESULTS_DIR, exist_ok=True)

print("Project directory:", PROJECT_DIR)
print("Results directory:", RESULTS_DIR)

Cloning into '/content/negotiation_arena'...
remote: Enumerating objects: 210, done.
remote: Counting objects: 100% (210/210), done.
remote: Compressing objects: 100% (86/86), done.
remote: Total 210 (delta 136), reused 193 (delta 119), pack-reused 0 (from 0)
Receiving objects: 100% (210/210), 1.07 MiB | 17.88 MiB/s, done.
Resolving deltas: 100% (136/136), done.
Project directory: /content/negotiation_arena
Results directory: /content/negotiation_arena/results

In [4]:
human_data_path = os.path.join(
    PROJECT_DIR,
    "data",
    "processed",
    "human_negotiations.csv"
)

human_df = pd.read_csv(human_data_path)

print(human_df.shape)
human_df.head()

(4993, 8)

,dialogue_id,split,turn_id,role,text,act,issue,value
0,0,train,0,Candidate,Hello. I would like to discuss the issues of m...,Greet,NaN,True
1,0,train,1,Candidate,I would like a position of project manager,Offer,Job Description,Project Manager
2,0,train,2,Employer,We do not have any project manager positions o...,Reject,Job Description,Project Manager
3,0,train,3,Candidate,I want a position of project manager,Offer,Job Description,Project Manager
4,0,train,4,Employer,I do have programmer positions open with a str...,Offer,Job Description,Programmer

In [5]:
human_df.shape

(4993, 8)

In [6]:
human_df["dialogue_id"].nunique()

105

In [7]:
model_id = "TinyLlama/TinyLlama-1.1B-Chat-v1.0"

pipe = pipeline(
    "text-generation",
    model=model_id,
    torch_dtype=torch.float16,
    device_map="auto"
)

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:93: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

config.json:   0%|          | 0.00/608 [00:00<?, ?B/s]

`torch_dtype` is deprecated! Use `dtype` instead!

model.safetensors:   0%|          | 0.00/2.20G [00:00<?, ?B/s]

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/124 [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

tokenizer.model:   0%|          | 0.00/500k [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

special_tokens_map.json:   0%|          | 0.00/551 [00:00<?, ?B/s]

In [8]:
def generate_response(system_prompt, user_message, max_new_tokens=180):
    prompt = f"""
<|system|>
{system_prompt}

<|user|>
{user_message}

<|assistant|>
"""

    output = pipe(
        prompt,
        max_new_tokens=max_new_tokens,
        do_sample=True,
        temperature=0.7,
        top_p=0.9,
        return_full_text=False,
        pad_token_id=pipe.tokenizer.eos_token_id
    )

    return output[0]["generated_text"].strip()

In [9]:
NEGOTIATION_ACTS = ["Offer", "Reject", "Query", "Accept"]

def get_first_negotiation_act(human_df, dialogue_id):
    dialogue = human_df[
        (human_df["dialogue_id"].astype(str) == str(dialogue_id)) &
        (human_df["act"].isin(NEGOTIATION_ACTS))
    ].sort_values("turn_id")

    if dialogue.empty:
        return None

    return dialogue.iloc[0]

In [10]:
#test for first act
first_act = get_first_negotiation_act(human_df, human_df["dialogue_id"].iloc[0])
first_act

dialogue_id                                             0
split                                               train
turn_id                                                 1
role                                            Candidate
text           I would like a position of project manager
act                                                 Offer
issue                                     Job Description
value                                     Project Manager
Name: 1, dtype: object

In [11]:
def build_agent_prompt(role):
    return f"""
You are the {role} in a job contract negotiation.

You are continuing a negotiation that started from a real human negotiation act.

Your goal:
- negotiate realistically
- respond according to your role
- use offers, counteroffers, rejections, questions, or acceptance when appropriate
- avoid repeating the same message
- try to reach an agreement if possible
- if no progress is made after repeated disagreement, end the negotiation

Use one of these dialogue acts:
Offer, Accept, Reject, Query, Quit, Other

Rules:
- If you accept the other party's proposal, write ACT: Accept and DECISION: accept.
- If the negotiation is clearly stuck or no compromise is possible, write ACT: Quit and DECISION: quit.
- If you are still negotiating, write DECISION: continue.

Reply ONLY in this format:

MESSAGE: your short negotiation message
ACT: Offer / Accept / Reject / Query / Quit / Other
ISSUE: negotiated issue or NONE
VALUE: proposed value or NONE
DECISION: continue / accept / quit
"""

In [12]:
def parse_llm_act_response(text):
    result = {
        "message": None,
        "act": None,
        "issue": None,
        "value": None,
        "decision": None
    }

    for line in text.splitlines():
        line = line.strip()

        if line.startswith("MESSAGE:"):
            result["message"] = line.replace("MESSAGE:", "").strip()

        elif line.startswith("ACT:"):
            result["act"] = line.replace("ACT:", "").strip()

        elif line.startswith("ISSUE:"):
            value = line.replace("ISSUE:", "").strip()
            result["issue"] = None if value.upper() == "NONE" else value

        elif line.startswith("VALUE:"):
            value = line.replace("VALUE:", "").strip()
            result["value"] = None if value.upper() == "NONE" else value

        elif line.startswith("DECISION:"):
            result["decision"] = line.replace("DECISION:", "").strip().lower()

    return result

In [13]:
def build_seed_message(first_act):
    return f"""
The following is the first substantive negotiation act from a human job negotiation.

Speaker: {first_act["role"]}
Utterance: {first_act["text"]}
Dialogue act: {first_act["act"]}
Issue: {first_act["issue"]}
Value: {first_act["value"]}

Continue the negotiation from this point.
"""

In [14]:
def get_next_speaker(role):
    if role == "Candidate":
        return "Employer"
    elif role == "Employer":
        return "Candidate"
    else:
        return "Employer"

In [15]:
def run_human_seeded_simulation(human_df, dialogue_id, max_cap=20):
    first_act = get_first_negotiation_act(human_df, dialogue_id)

    if first_act is None:
        return [], {
            "dialogue_id": dialogue_id,
            "outcome": "NoSeed",
            "n_turns": 0,
            "human_original_turns": 0,
            "seed_role": None,
            "seed_act": None,
            "seed_issue": None,
            "seed_value": None
        }

    human_dialogue = human_df[
        human_df["dialogue_id"].astype(str) == str(dialogue_id)
    ]

    human_length = human_dialogue["turn_id"].nunique()
    max_turns = min(human_length, max_cap)

    seed_message = build_seed_message(first_act)

    conversation_log = []

    conversation_log.append({
        "dialogue_id": dialogue_id,
        "turn": 0,
        "speaker": first_act["role"],
        "text": first_act["text"],
        "act": first_act["act"],
        "issue": first_act["issue"],
        "value": first_act["value"],
        "decision": "seed",
        "is_seed": True
    })

    current_message = seed_message
    current_speaker = get_next_speaker(first_act["role"])

    outcome = None

    for turn in range(1, max_turns + 1):

        system_prompt = build_agent_prompt(current_speaker)

        llm_text = generate_response(
            system_prompt,
            current_message
        )

        parsed = parse_llm_act_response(llm_text)

        conversation_log.append({
            "dialogue_id": dialogue_id,
            "turn": turn,
            "speaker": current_speaker,
            "text": llm_text,
            "act": parsed["act"],
            "issue": parsed["issue"],
            "value": parsed["value"],
            "decision": parsed["decision"],
            "is_seed": False
        })

        if parsed["decision"] == "accept" or parsed["act"] == "Accept":
            outcome = "Agreement"
            break

        if parsed["decision"] == "quit" or parsed["act"] == "Quit":
            outcome = "Failure"
            break

        recent_context = conversation_log[-6:]

        context_text = ""
        for row in recent_context:
            context_text += f'{row["speaker"]}: {row["text"]}\n'

        next_speaker = get_next_speaker(current_speaker)

        current_message = f"""
Continue the following job negotiation.

Recent conversation:
{context_text}

Now reply as {next_speaker}.
"""

        current_speaker = next_speaker

    if outcome is None:
        recent_non_seed = [
            row for row in conversation_log[-6:]
            if row["is_seed"] == False
        ]

        recent_acts = [
            str(row["act"]).lower()
            for row in recent_non_seed
            if row["act"] is not None
        ]

        recent_decisions = [
            str(row["decision"]).lower()
            for row in recent_non_seed
            if row["decision"] is not None
        ]

        recent_texts = [
            str(row["text"]).lower()
            for row in recent_non_seed
            if row["text"] is not None
        ]

        recent_text = " ".join(recent_texts)

        impasse_keywords = [
            "cannot accept",
            "can't accept",
            "not acceptable",
            "too low",
            "too high",
            "below my minimum",
            "above our maximum",
            "no agreement",
            "unable to agree",
            "end the negotiation",
            "walk away"
        ]

        if (
            "reject" in recent_acts
            or recent_decisions.count("continue") >= 4
            or any(keyword in recent_text for keyword in impasse_keywords)
        ):
            outcome = "Impasse"
        else:
            outcome = "Timeout"

    outcome_row = {
        "dialogue_id": dialogue_id,
        "outcome": outcome,
        "n_turns": len(conversation_log),
        "human_original_turns": human_length,
        "seed_role": first_act["role"],
        "seed_act": first_act["act"],
        "seed_issue": first_act["issue"],
        "seed_value": first_act["value"]
    }

    return conversation_log, outcome_row

In [16]:
##test on 3 dialogues

test_dialogues = human_df["dialogue_id"].astype(str).unique()[:3]

test_turns = []
test_outcomes = []

for dialogue_id in test_dialogues:
    print("Running test dialogue:", dialogue_id)

    log, outcome = run_human_seeded_simulation(
        human_df,
        dialogue_id,
        max_cap=10
    )

    test_turns.extend(log)
    test_outcomes.append(outcome)

test_turns_df = pd.DataFrame(test_turns)
test_outcomes_df = pd.DataFrame(test_outcomes)

test_outcomes_df

Passing `generation_config` together with generation-related arguments=({'pad_token_id', 'temperature', 'max_new_tokens', 'do_sample', 'top_p'}) is deprecated and will be removed in future versions. Please pass either a `generation_config` object OR all generation parameters explicitly, but not both.
Both `max_new_tokens` (=180) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Running test dialogue: 0

Both `max_new_tokens` (=180) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=180) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=180) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Running test dialogue: 1

Both `max_new_tokens` (=180) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=180) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=180) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=180) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=180) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=180) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
Both `max_new_tokens` (=180) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=180) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=180) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=180) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Running test dialogue: 10

Both `max_new_tokens` (=180) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=180) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=180) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=180) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=180) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=180) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=180) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=180) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=180) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

,dialogue_id,outcome,n_turns,human_original_turns,seed_role,seed_act,seed_issue,seed_value
0,0,Agreement,4,55,Candidate,Offer,Job Description,Project Manager
1,1,Timeout,11,27,Candidate,Offer,Job Description,Project Manager
2,10,Timeout,11,63,Candidate,Offer,Job Description,Project Manager

In [17]:
test_turns_df.head(20)

,dialogue_id,turn,speaker,text,act,issue,value,decision,is_seed
0,0,0,Candidate,I would like a position of project manager,Offer,Job Description,Project Manager,seed,True
1,0,1,Employer,Speaker: Candidate\nUtterance: Based on the pr...,None,None,None,None,False
2,0,2,Candidate,MESSAGE: Thank you for your interest in the pr...,Offer / Accept / Reject / Query / Quit / Other,Job Description / Project Manager / No Issue,Project Manager / No Value,continue / accept / reject / query / quit,False
3,0,3,Employer,MESSAGE: Thank you for your interest in the pr...,Offer / Accept / Reject / Query / Quit / Other,Job Description / Project Manager / No Issue,Project Manager / No Value,accept,False
4,1,0,Candidate,I am expecting a position of project manager,Offer,Job Description,Project Manager,seed,True
5,1,1,Employer,Speaker: Candidate\nUtterance: I am expecting ...,None,None,None,None,False
6,1,2,Candidate,Speaker: Candidate\nUtterance: I appreciate yo...,None,None,None,None,False
7,1,3,Employer,Speaker: Employer\nUtterance: Candidate\n\nUtt...,None,None,None,None,False
8,1,4,Candidate,Candidate: Thank you for your interest in the ...,None,None,None,None,False
9,1,5,Employer,Candidate: Speaker: Candidate\nUtterance: I ap...,None,None,None,None,False
10,1,6,Candidate,Candidate: Speaker: Candidate\nUtterance: I ap...,None,None,None,None,False
11,1,7,Employer,MESSAGE: Your short negotiation message\nACT: ...,Offer,Negotiated issue or NONE,proposed value or NONE,continue,False
12,1,8,Candidate,Candidate: Speaker: Candidate\nUtterance: I ap...,None,None,None,None,False
13,1,9,Employer,MESSAGE: Your short negotiation message\nACT: ...,Offer,Negotiated issue or NONE,proposed value or NONE,continue,False
14,1,10,Candidate,Recent conversation:\nCandidate: Candidate: Th...,None,None,None,None,False
15,10,0,Candidate,I would like a position of project manager,Offer,Job Description,Project Manager,seed,True
16,10,1,Employer,Speaker: Employer\nUtterance: I would like a p...,None,None,None,None,False
17,10,2,Candidate,MESSAGE: Your short negotiation message\nACT: ...,Offer / Accept / Reject / Query / Quit / Other,negotiated issue or NONE,proposed value or NONE,continue,False
18,10,3,Employer,Employer: Speaker: Employer\nUtterance: I woul...,None,None,None,None,False
19,10,4,Candidate,MESSAGE: Your short negotiation message\nACT: ...,Offer / Accept / Reject / Query / Quit / Other,negotiated issue or NONE,proposed value or NONE,continue,False

In [18]:
import random

random.seed(42)

all_dialogues = human_df["dialogue_id"].astype(str).unique().tolist()

sample_size = 20

sample_dialogues = random.sample(
    all_dialogues,
    min(sample_size, len(all_dialogues))
)

print("Number of sampled dialogues:", len(sample_dialogues))
print(sample_dialogues)

Number of sampled dialogues: 20
['78', '17', '100', '9', '36', '32', '3', '2', '16', '82', '67', '14', '72', '53', '101', '29', '30', '62', '74', '69']

In [19]:
human_seeded_turns = []
human_seeded_outcomes = []

for dialogue_id in tqdm(sample_dialogues):
    log, outcome = run_human_seeded_simulation(
        human_df,
        dialogue_id,
        max_cap=20
    )

    human_seeded_turns.extend(log)
    human_seeded_outcomes.append(outcome)

    pd.DataFrame(human_seeded_turns).to_csv(
       os.path.join(RESULTS_DIR, "human_seeded_llm_turns_sample.csv"),
        index=False
    )

    pd.DataFrame(human_seeded_outcomes).to_csv(
        os.path.join(RESULTS_DIR, "human_seeded_llm_outcomes_sample.csv"),
        index=False
    )

human_seeded_turns_df = pd.DataFrame(human_seeded_turns)
human_seeded_outcomes_df = pd.DataFrame(human_seeded_outcomes)

human_seeded_outcomes_df

  0%|          | 0/20 [00:00<?, ?it/s]Both `max_new_tokens` (=180) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=180) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
  5%|▌         | 1/20 [00:11<03:34, 11.31s/it]Both `max_new_tokens` (=180) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=180) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=180) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 10%|█         | 2/20 [00:25<03:53, 12.99s/it]Both `max_new_tokens` (=180) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=180) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=180) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=180) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=180) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=180) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=180) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=180) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=180) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 15%|█▌        | 3/20 [01:17<08:44, 30.84s/it]Both `max_new_tokens` (=180) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=180) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=180) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=180) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=180) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=180) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=180) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=180) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 20%|██        | 4/20 [02:04<09:58, 37.39s/it]Both `max_new_tokens` (=180) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=180) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=180) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=180) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=180) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=180) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=180) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=180) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=180) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=180) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=180) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=180) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=180) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=180) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=180) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=180) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=180) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=180) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 25%|██▌       | 5/20 [03:51<15:34, 62.29s/it]Both `max_new_tokens` (=180) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=180) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=180) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=180) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=180) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=180) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=180) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=180) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=180) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=180) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=180) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=180) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=180) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=180) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=180) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=180) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=180) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=180) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=180) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=180) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 30%|███       | 6/20 [05:51<19:08, 82.06s/it]Both `max_new_tokens` (=180) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=180) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 35%|███▌      | 7/20 [06:03<12:47, 59.04s/it]Both `max_new_tokens` (=180) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=180) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=180) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=180) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=180) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=180) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=180) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 40%|████      | 8/20 [06:42<10:33, 52.77s/it]Both `max_new_tokens` (=180) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=180) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=180) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=180) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=180) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=180) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=180) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=180) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=180) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

,dialogue_id,outcome,n_turns,human_original_turns,seed_role,seed_act,seed_issue,seed_value
0,78,Agreement,3,47,Candidate,Offer,Job Description,Project Manager
1,17,Agreement,4,48,Candidate,Offer,Salary,"120,000 USD"
2,100,Agreement,10,43,Candidate,Offer,Job Description,Project Manager
3,9,Agreement,9,23,Candidate,Offer,Salary,"120,000 USD"
4,36,Impasse,19,18,Candidate,Offer,Job Description,Project Manager
5,32,Timeout,21,27,Candidate,Offer,Job Description,Project Manager
6,3,Agreement,3,32,Candidate,Offer,Salary,"120,000 USD"
7,2,Agreement,8,16,Candidate,Offer,Salary,"120,000 USD"
8,16,Impasse,15,14,Candidate,Offer,Job Description,Project Manager
9,82,Timeout,21,29,Candidate,Offer,Job Description,Project Manager
10,67,Timeout,21,20,Candidate,Offer,Job Description,Project Manager
11,14,Agreement,3,27,Candidate,Offer,Job Description,Project Manager
12,72,Agreement,2,12,Candidate,Offer,Job Description,Project Manager
13,53,Timeout,21,55,Candidate,Offer,Job Description,Project Manager
14,101,Timeout,21,26,Candidate,Offer,Salary,"120,000 USD"
15,29,Agreement,2,35,Candidate,Offer,Job Description,Project Manager
16,30,Timeout,21,37,Candidate,Offer,Job Description,Project Manager
17,62,Agreement,2,23,Candidate,Offer,Job Description,Project Manager
18,74,Timeout,21,40,Candidate,Offer,Job Description,Project Manager
19,69,Timeout,21,21,Candidate,Offer,Job Description,Project Manager

In [20]:
human_seeded_outcomes_df["outcome"].value_counts()

outcome
Agreement    10
Timeout       8
Impasse       2
Name: count, dtype: int64

In [21]:
human_seeded_outcomes_df["n_turns"].describe()

count    20.000000
mean     12.400000
std       8.394234
min       2.000000
25%       3.000000
50%      12.500000
75%      21.000000
max      21.000000
Name: n_turns, dtype: float64

In [22]:
human_seeded_outcomes_df.head()

,dialogue_id,outcome,n_turns,human_original_turns,seed_role,seed_act,seed_issue,seed_value
0,78,Agreement,3,47,Candidate,Offer,Job Description,Project Manager
1,17,Agreement,4,48,Candidate,Offer,Salary,"120,000 USD"
2,100,Agreement,10,43,Candidate,Offer,Job Description,Project Manager
3,9,Agreement,9,23,Candidate,Offer,Salary,"120,000 USD"
4,36,Impasse,19,18,Candidate,Offer,Job Description,Project Manager

In [23]:
human_seeded_outcomes_df["turn_difference"] = (
    human_seeded_outcomes_df["n_turns"]
    - human_seeded_outcomes_df["human_original_turns"]
)

human_seeded_outcomes_df[[
    "dialogue_id",
    "outcome",
    "n_turns",
    "human_original_turns",
    "turn_difference"
]].head()

  dialogue_id    outcome  n_turns  human_original_turns  turn_difference
0          78  Agreement        3                    47              -44
1          17  Agreement        4                    48              -44
2         100  Agreement       10                    43              -33
3           9  Agreement        9                    23              -14
4          36    Impasse       19                    18                1

In [24]:
human_seeded_outcomes_df[["n_turns", "human_original_turns"]].mean()

n_turns                 12.40
human_original_turns    29.65
dtype: float64

In [25]:
from google.colab import files

files.download(os.path.join(RESULTS_DIR, "human_seeded_llm_turns_sample.csv"))
files.download(os.path.join(RESULTS_DIR, "human_seeded_llm_outcomes_sample.csv"))